name = "naderclass"
main = "index.js"
compatibility_date = "2026-08-01"

[[kv_namespaces]]
binding = "EXAM_KV"
id = "9eef2cd7d7ff4d5187a7728eef68d718"

[[durable_objects.bindings]]
name = "CLASSROOM"
class_name = "ClassRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClassRoom"]

